### PR TITLE
Fix #67

### LINKED ISSUE #67: Boomer breaks if config has an empty line
I tried making a config and it had an empty line in it. When I ran boomer i got
```
fatal.nim(39)            sysFatal
Error: unhandled exception: index 1 not in 0 .. 0 [IndexError]
```
Then I removed the empty line, and it worked as expected.

### PR DESCRIPTION
**Pull request by Antzelino**
Now config file can have empty lines without breaking boomer

### CODE REVIEW

File: src/config.nim [hunk 1]
```diff
@@ -36,6 +36,8 @@ macro parseObject(obj: typed, key, val: string) =
 proc loadConfig*(filePath: string): Config =
   result = defaultConfig
   for rawLine in filePath.lines:
+    if rawLine.len == 0:
+      continue
```
Comment (rexim) [inline src/config.nim]: This doesn't fully address the root cause of the bug. Non-empty lines consisting of only whitespaces also crash the application.

Comment (Antzelino) [reply src/config.nim]: Indeed. I do not know nim so that's all I could do. Maybe if you check `pair.len == 0` after https://github.com/tsoding/boomer/blob/8e8f37fa0a222c807d35f5192bedbdc2f4851b65/src/config.nim#L42 ? And in case it is indeed 0, you `continue`

Comment (rexim) [reply src/config.nim]: Why do you think `pair.len == 0` in case of an empty string?

Comment (Antzelino) [reply src/config.nim]: Doesn't matter. I solved it after all, should I make a new pull request?

File: src/config.nim [hunk 2]
```diff
@@ -36,6 +36,8 @@ macro parseObject(obj: typed, key, val: string) =
...
     let line = rawLine.strip
     if line.len > 0 and line[0] == '#':
```
Comment (SolitudeSF) [inline src/config.nim]:
```suggestion
    if (line.len > 0 and line[0] == '#') or line.len == 0:
```

Comment (SolitudeSF) [reply src/config.nim]: here, this is most optimal. i would drop `continue` entirely, but please, dont introduce another one + redundant if condition.

Comment (Antzelino) [reply src/config.nim]: I haven't seen anywhere in the if's any parentheses so i wanted to keep it consistent, plus the different if's for me show that they have different reasons to be there (one for empty lines and the other for comment lines)

Comment (SolitudeSF) [reply src/config.nim]: condition i suggest is already self-explanatory. and there are no parentheses.

Comment (Antzelino) [reply src/config.nim]: ok, after checking a little more, there are some cases with parentheses in if statements (in boomer.nim) but i think i still like it more this way. sometimes i prefer to lose some from "optimal" to gain in "clean"

Comment (Antzelino) [reply src/config.nim]: oh i just realized you edited it. ok i like it more with the new edit

**Comment by rexim** [comment]
@Antzelino @SolitudeSF looks good to me! :+1: Thank you guys for the contribution!
